org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.java.home=C\:/Program Files/Android/Android Studio/jbr
org.gradle.parallel=true

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.bundle.includeNativeDebugMetadata=false

kotlin.code.style=official
org.gradle.welcome=never

unityStreamingAssets=
unityTemplateVersion=25
unityProjectPath=C\:/UnityProjects/NicaExplorer
unity.projectPath=C\:/UnityProjects/NicaExplorer
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=30
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.lospuntoycoma.nicaexplorer
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=0.1.0
unity.namespace=com.lospuntoycoma.nicaexplorer
unity.agpVersion=9.0.0
unity.androidSdkPath=C\:/Program Files/Unity/Hub/Editor/6000.5.1f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C\:/Program Files/Unity/Hub/Editor/6000.5.1f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C\:/Program Files/Unity/Hub/Editor/6000.5.1f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
